Feature/login
web-architectures-project/SkillVista-frontend pull request #17
Opened 2023-10-14 16:37 UTC by call203

- Add Request API
- connect to Login and Register API 

Hey guys, I think we should arrange our response message for the frontend.
I'll be setting cookie and addressing some the error responses in backend

2023-10-14 17:44 UTC, 1Solon requested changes
Check my comments. The localhost thing needs changing, the other one is just an advisory,

2023-10-14 17:44 UTC, 1Solon commented on .env
> +NEXT_PUBLIC_API_URL = http://localhost:3001/
Backend (without docker) currently uses 3001, this should be something else by default.

2023-10-14 17:44 UTC, 1Solon commented on next.config.js
> +        destination: 'http://localhost:3001/:path*',
Same here

2023-10-14 17:44 UTC, 1Solon commented on src/pages/user-registration/index.tsx
The backend (should) support form validation by default, if you want to do less work (up to you) you can probably just check for the errors instead of writing the logic here.

2023-10-18 09:57 UTC, call203 commented on next.config.js
> +        destination: 'http://localhost:3001/:path*',
I changed to localhost:3000
This setting is for front-end API Routes, which is used for session

2023-10-18 09:58 UTC, call203 commented on src/pages/user-registration/index.tsx
I've only fixed UI in this page. Logic is written by @KaustubhTrivedi .
Anyway, you are right

2023-10-18 10:03 UTC, KaustubhTrivediTuDublin approved these changes

2023-10-18 10:04 UTC, KaustubhTrivedi approved these changes

2023-10-18 10:10 UTC, merged